config_file = "launch.toml"
use_gpu = true
target_md5 = "5d41402abc4b2a76b9719d911017c592"
num_threads = 1000
chunk_size = 100000
verbosity = 4
savefile = "savefile.dat"
result_file= "results.csv"
restore_from_file = false
use_mpi = true
#dictionary = "./dictionary.txt"
dictionary = "NONE"
brutestart = 4
cluster_degree= 2