config_file = "launch.toml"
use_gpu = true
#target_md5 = "98abe3a28383501f4bfd2d9077820f11" #!!!!
#target_md5 = "addec426932e71323700afa1911f8f1c" #more
target_md5 = "952bccf9afe8e4c04306f70f7bed6610" # !!!!!
num_threads = 1000
chunk_size = 100000
verbosity = 4
savefile = "savefile.dat"
result_file= "results.csv"
restore_from_file = false
use_mpi = true
#dictionary = "./dictionary.txt"
dictionary = "NONE"
brutestart = 4
cluster_degree= 0