config_file = "launch.toml"
use_gpu = true
target_md5 = "df0ab011de60a20038a6d5fd760de52e"
num_threads = 1000
chunk_size = 1000
verbosity = 4
savefile = "savefile.dat"
result_file= "results.csv"
restore_from_file = false
use_mpi = true
#dictionary = "./dictionary.txt"
dictionary = "NONE"
brutestart = 4